@URL_API = http://localhost:3000
@JWT_TOKEN = {{loginUser.response.body.accessToken}}

@UserTestEmail =  email@exemplo.com
@UserTestPassword = 123456
@UserTestName = teste

@UserTestEmailPatch = email@exemplo.com.br
@UserTestPasswordPatch = 1234567
@UserTestNamePatch = example

@SlugID = macaco-dos-chama-loose-xaovwa
@PostUUID = 70505059-ef36-477e-a1df-e162557ecbf9
### Login
# @name loginUser
POST {{URL_API}}/auth/login
Content-Type: application/json

{
  "email": "{{UserTestEmail}}",
  "password": "{{UserTestPassword}}"
}

### GetUser
GET {{URL_API}}/user/me
Content-Type: application/json
Authorization: Bearer {{JWT_TOKEN}}

### CreateUser
# @name createUser
POST {{URL_API}}/user
Content-Type: application/json

{
  "email": "{{UserTestEmail}}",
  "password": "{{UserTestPassword}}",
  "name": "{{UserTestName}}"
}

### UpdateUser
# @name updateUser
PATCH {{URL_API}}/user/me
Content-Type: application/json
Authorization: Bearer {{JWT_TOKEN}}

{
  "email": "{{UserTestEmailPatch}}",
  "name": "{{UserTestNamePatch}}"
}

### Login
# @name updateUserPassword
PATCH {{URL_API}}/user/me/password
Content-Type: application/json
Authorization: Bearer {{JWT_TOKEN}}

{
  "currentPassword": "{{UserTestPassword}}",
  "newPassword": "{{UserTestPasswordPatch}}"
}

### GetOneUser
# @name getOneUser
GET {{URL_API}}/user/me
Content-Type: application/json
Authorization: Bearer {{JWT_TOKEN}}

### DeleteOnUser
# @name deleteOnUser
DELETE {{URL_API}}/user/me
Content-Type: application/json
Authorization: Bearer {{JWT_TOKEN}}

### CreatePost
# @name createPost
POST {{URL_API}}/post
Content-Type: application/json
Authorization: Bearer {{JWT_TOKEN}}

{
  "title": "macaco dos chama loose",
  "excerpt": "faz o l caralho",
  "content": "faz o l ricardo"
}

### GetPostBySlug
# @name getPostBySlug
GET  {{URL_API}}/post/{{SlugID}}

### GetMyPostById
# @name getMyPostById
GET  {{URL_API}}/post/me/{{PostUUID}}
Authorization: Bearer {{JWT_TOKEN}}

### GetAllMyPost
# @name getAllMyPost
GET  {{URL_API}}/post/me
Authorization: Bearer {{JWT_TOKEN}}

### GetAllPost
# @name getAllPosts
GET  {{URL_API}}/post

### UpdatePost
# @name PatchPost
PATCH {{URL_API}}/post/me/{{PostUUID}}
Content-Type: application/json
Authorization: Bearer {{JWT_TOKEN}}

{
  "coverImageUrl": "http://localhost",
  "published": true
}

### DeletePost
# @name DeletePost
Delete {{URL_API}}/post/me/{{PostUUID}}
Content-Type: application/json
Authorization: Bearer {{JWT_TOKEN}}

### uploadImage
# @name UploadImage
POST {{URL_API}}/file/upload
Content-Type: multipart/form-data; boundary=----FormBoundary
Authorization: Bearer {{JWT_TOKEN}}

------FormBoundary
Content-Disposition: form-data; name="file"; filename="comment_photo.jpg"
Content-Type: image/jpeg

< ./comment_photo.jpg
------FormBoundary--
