@URL_API = http://localhost:3000
@JWT_TOKEN = {{loginUser.response.body.accessToken}}

### Login
# @name loginUser
POST {{URL_API}}/auth/login
Content-Type: application/json

{
  "email": "email@exemplo.com",
  "password": "123456"
}

### GetUser
GET {{URL_API}}/user/123
Content-Type: application/json
Authorization: Bearer {{JWT_TOKEN}}

### CreateUser
# @name createUser
POST {{URL_API}}/user
Content-Type: application/json

{
  "email": "email@exemplo.com",
  "password": "123456",
  "name": "teste"
}

### UpdateUser
# @name updateUser
PATCH {{URL_API}}/user/me
Content-Type: application/json
Authorization: Bearer {{JWT_TOKEN}}

{
  "email": "email@exemplo.com",
  "name": "example"
}

### Login
# @name updateUserPassword
PATCH {{URL_API}}/user/me/password
Content-Type: application/json
Authorization: Bearer {{JWT_TOKEN}}

{
  "currentPassword": "1234567",
  "newPassword": "123456"
}
